from .user import UserResource
from .unit import UnitResource
#from .tenant import TenantResource
from .lease import LeaseAgreementResource
from .payment import PaymentResource
from .bill import BillResource
from .cms import CmsResource
from .accesscontrol import AccessControlResource
from .feedback_complaint_notes import FeedbackComplaintNotesResource