"""Change units user_id to be nullable

Revision ID: 120353a6e18e
Revises: 2ee72b2d84e4
Create Date: 2024-02-04 02:23:38.012204

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '120353a6e18e'
down_revision = '2ee72b2d84e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('sq_foot',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('number_of_bedrooms',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
        batch_op.alter_column('number_of_bathrooms',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('units', schema=None) as batch_op:
        batch_op.alter_column('number_of_bathrooms',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('number_of_bedrooms',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('sq_foot',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    # ### end Alembic commands ###
