"""New Entry to add

Revision ID: 6f6add2f7b55
Revises: 120353a6e18e
Create Date: 2024-02-09 04:58:52.079418

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6f6add2f7b55'
down_revision = '120353a6e18e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bill_type', sa.Enum('UTILITY', 'ASSOCIATION', 'PARKING', 'MAINTENANCE', 'INTERNETCABLE', 'ETC', name='bill_type'), nullable=False))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=50), nullable=True))

    with op.batch_alter_table('lease_agreements', schema=None) as batch_op:
        batch_op.alter_column('security_deposit',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=50),
               nullable=True)

    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('move_in_date',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.alter_column('move_in_date',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_method',
               existing_type=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('lease_agreements', schema=None) as batch_op:
        batch_op.alter_column('security_deposit',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('bill_type')

    # ### end Alembic commands ###
