"""Make bill_type be nullable for now

Revision ID: e2a1b1682bf2
Revises: 0dbdd6a52a04
Create Date: 2024-02-10 05:45:10.267367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e2a1b1682bf2'
down_revision = '0dbdd6a52a04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('bill_type',
               existing_type=mysql.ENUM('UTILITY', 'ASSOCIATION', 'PARKING', 'MAINTENANCE', 'INTERNETCABLE', 'ETC'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.alter_column('bill_type',
               existing_type=mysql.ENUM('UTILITY', 'ASSOCIATION', 'PARKING', 'MAINTENANCE', 'INTERNETCABLE', 'ETC'),
               nullable=False)

    # ### end Alembic commands ###
